# Generated by Django 4.2.2 on 2024-02-18 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ONB_admin", "0002_notification_title"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="file",),
        migrations.RemoveField(model_name="notification", name="receiver",),
    ]
